test
ibardych/goit_js_team_project pull request #2
Opened 2023-03-03 12:44 UTC by Alenamasha

2023-03-03 12:45 UTC, ibardych commented
test

2023-03-03 12:46 UTC, ibardych requested changes
будь ласка доповни код

2023-03-04 08:22 UTC, ibardych requested changes
Все дуж класно!
Але ще потрібно деталі доробити:
• використай кнопку заготовку
<button class="button-more" type="button">Button Name</button>
і щоб відступи всередині зліва і справа були такі я в тебе мають бути, додай клас модифікатор для неї у своїх стилях.
• зроби хрестик анімованим, додай в стилях міксін
@include transition(opacity);
і ще зміни відображення курсора на cursor: pointer;
• Висота модального вікна напевне буде різною взалежності від наповнення. Не задавай сталу висоту. min-height не потрібне.
• Зроби відображення вікна по центру екрану

2023-03-04 22:41 UTC, ibardych requested changes
написав в телеграмі

2023-03-05 10:49 UTC, ibardych approved these changes

2023-03-05 10:59 UTC, AntonTsyrkunov approved these changes

2023-03-05 10:59 UTC, merged